### ISSUE TITLE
Issue running install.bat and api.bat

### ISSUE THREAD

**Issue by FatFaut** [aziib/YoutubeLiveChatLocalApi#1]
Hello, I have an issue where whenever I try to run install.bat it would output this:

ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
Requirement already satisfied: pytchat in c:\users\blank\documents\silly\sillytavern-launcher\public\scripts\extensions\third-party\youtubelivechatlocalapi\venv\lib\site-packages (from -r requirements.txt (line 1)) (0.5.5)
Requirement already satisfied: Flask in c:\users\blank\documents\silly\sillytavern-launcher\public\scripts\extensions\third-party\youtubelivechatlocalapi\venv\lib\site-packages (from -r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: Flask-Cache in c:\users\blank\documents\silly\sillytavern-launcher\public\scripts\extensions\third-party\youtubelivechatlocalapi\venv\lib\site-packages (from -r requirements.txt (line 3)) (0.13.1)
Requirement already satisfied: Flask-Cors in c:\users\blank\documents\silly\sillytavern-launcher\public\scripts\extensions\third-party\youtubelivechatlocalapi\venv\lib\site-packages (from -r requirements.txt (line 4)) (4.0.1)
**ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json**

I tried removing "json" from requirements.txt after reading that python has a built in json module and ran into an error when trying to launch api.bat which output this:

Traceback (most recent call last):
  File "C:\Users\blank\Documents\Silly\SillyTavern-Launcher\public\scripts\extensions\third-party\YoutubeLiveChatLocalApi\app.py", line 2, in <module>
    from flask_caching import Cache
ModuleNotFoundError: No module named 'flask_caching'
Press any key to continue . . .

I tried uninstalling and reinstalling the entire folder, as well as flask and flask_caching from the library which had no effect. I also tried renaming flask_cache to flask_caching after finding Cache was defined there in __init__, which gave me another error with werkzeug. 

I have java version 1.8.0_421 and python 3.11.9 installed and the folder is located in the third party folder alongside Extension-LiveChat.

**Comment by aziib** [comment]
try installing Flask-Caching using this command:
pip install Flask-Caching

if not work, try install manually using python 3.10
make the virtual environment using this command
python3.10 -m venv venv
